services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
    networks:
      - catequesis_net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - catequesis_net

networks:
  catequesis_net:
    driver: bridge
